### ISSUE TITLE
Issue with restart

### ISSUE THREAD

**Issue by hlyl** [schana/dayz-mod-party#12]
continue to write the followin in the Script Log:
SCRIPT       : [SchanaParty] SendInfo
SCRIPT       : [SchanaParty] Positions {}
SCRIPT       : [SchanaParty] Healths {}
SCRIPT       : [SchanaParty] Parties {}
SCRIPT       : [SchanaParty] SendPlayers {"param1":[],"param2":[]}
SCRIPT       : [SchanaParty] SendInfo
SCRIPT       : [SchanaParty] Positions {}
SCRIPT       : [SchanaParty] Healths {}
SCRIPT       : [SchanaParty] Parties {}
SCRIPT       : [SchanaParty] SendPlayers {"param1":[],"param2":[]}
SCRIPT       : [SchanaParty] SendInfo
SCRIPT       : [SchanaParty] Positions {}
SCRIPT       : [SchanaParty] Healths {}
SCRIPT       : [SchanaParty] Parties {}
SCRIPT       : [SchanaParty] SendPlayers {"param1":[],"param2":[]}
SCRIPT       : [SchanaParty] SendInfo
SCRIPT       : [SchanaParty] Positions {}
SCRIPT       : [SchanaParty] Healths {}
SCRIPT       : [SchanaParty] Parties {}
SCRIPT       : [SchanaParty] SendPlayers {"param1":[],"param2":[]}
SCRIPT       : [SchanaParty] SendInfo
SCRIPT       : [SchanaParty] Positions {}
SCRIPT       : [SchanaParty] Healths {}
SCRIPT       : [SchanaParty] Parties {}
SCRIPT       : [SchanaParty] SendPlayers {"param1":[],"param2":[]}
SCRIPT       : [SchanaParty] SendInfo
SCRIPT       : [SchanaParty] Positions {}
SCRIPT       : [SchanaParty] Healths {}
SCRIPT       : [SchanaParty] Parties {}
SCRIPT       : [SchanaParty] SendPlayers {"param1":[],"param2":[]}
SCRIPT       : [SchanaParty] SendInfo
SCRIPT       : [SchanaParty] Positions {}
SCRIPT       : [SchanaParty] Healths {}
SCRIPT       : [SchanaParty] Parties {}
SCRIPT       : [SchanaParty] SendPlayers {"param1":[],"param2":[]}

**Comment by schana** [comment]
This is probably due to the Mass update that went awry.
