### ISSUE TITLE
Cropped Logging Report

### ISSUE THREAD

**Issue by SoLoRDM** [schana/dayz-mod-party#57]
Hi,
Not sure if this is a problem with the script logging or how the mod sends its logs to script logging but when I check for teaming via party mod logs in said file I only appear to be able to get a part of the party instead of the entire player lists. It gives me 5/6 parties but always ends with half a BI ID.

Each log instance is 1,023 long rather than the x amount.

Curious if you might know a work around or whether it just is what it is.

Thanks in advance.

**Comment by schana** [comment]
That's a known issue. The log lines are truncated.

**Comment by SoLoRDM** [comment]
Damn, thanks for the reply mate. Keep up the good work.
