### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by michak89** [schana/dayz-mod-party#59]
Client crashes when disconecting from server and trying to connect again from menu, something with heap size.
Some people noticed this too: https://steamcommunity.com/workshop/filedetails/discussion/2534883520/3487501375923038293/

**Comment by michak89** [comment]
I had an older version (that one without gui), looks like problem is solved with the newest one, sorry for spam.

**Comment by schana** [comment]
Should be resolved with latest commits.
