### ISSUE TITLE
Player removing a member doesn't always update member's party

### ISSUE THREAD

**Issue by hlyl** [schana/dayz-mod-party#6]
During our testing, there is a need to be able to "un-friend" a player that was on your list.
currently if I remove a player that I was Paired with, he continues to be able to see me event if  I have removed him from my list

**Comment by schana** [comment]
Looks like I forgot to have the client tell the server when a player is removed. Thank you for finding this!

**Comment by schana** [comment]
So I think I've narrowed down this bug. It seems to only occur when the last player was removed from an authorized party. The server wasn't sending updates for empty parties.
