### ISSUE TITLE
Issues loading party on restart

### ISSUE THREAD

**Issue by schana** [schana/dayz-mod-party#7]
players are reporting that it isnt working after restart, guessing they have to remove and re add to get it to work

**Comment by Braindead71** [comment]
1. After server restart, the party members are no longer visible to each other and you cannot Add or Remove. The buttons do nothing until you close the game completely and restart
2. When you die and respawn, it is the same as no 1. You cannot Add or Remove anyone

**Comment by schana** [comment]
9fce9f4868e03c46d5a997865ca38735909cffad Should fix at least part of this problem, if not all of it. Could you see if the issue is still occurring after updating to the latest version?

**Comment by Braindead71** [comment]
Hi

That seems to be working perfectly now.,.,. thank you.  As soon as we logged in, our party was there!  I also killed myself and respawned and the party was also there
Great mod and great work! thanks

**Comment by schana** [comment]
Glad it's working :)
