### ISSUE TITLE
Issue with showing party HP

### ISSUE THREAD

**Issue by MortyE2743** [schana/dayz-mod-party#8]
Issue showing player HP when entering within 1200m of each other. HP shows player as "red" or dead, but shows correct HP when player leaves the 1200m radius.

**Comment by schana** [comment]
This should have been fixed with 949c89803c9e11f37dfad1f5278c7f431b88d749

If it's still happening after updating to the latest version, please send me the `script` log from the client.

**Comment by MortyE2743** [comment]
Seems to be fixed with the latest update indeed.
